# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKvzRUUskEl4sBHF8ocpkDotUZ-XenMJ
"""

!pip install utils

from flask import Flask, request, jsonify
from utils import get_news_articles, analyze_sentiment_and_extract_topics, comparative_sentiment_analysis, generate_hindi_tts

app = Flask(__name__)

# API to fetch news and analyze sentiment
@app.route('/fetch_news', methods=['POST'])
def fetch_news():
    try:
        company_name = request.json['company_name']
        articles = get_news_articles(company_name)
        sentiment_results = []

        for article in articles:
            sentiment, topics = analyze_sentiment_and_extract_topics(article['summary'])
            sentiment_results.append({'title': article['title'], 'sentiment': sentiment, 'topics': topics})

        comparative_report = comparative_sentiment_analysis(sentiment_results)
        return jsonify({'status': 'success', 'report': comparative_report})

    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)})

# API to generate Hindi audio from summary
@app.route('/generate_audio', methods=['POST'])
def generate_audio():
    try:
        summary_text = request.json['summary_text']
        output_file = generate_hindi_tts(summary_text)
        return jsonify({'status': 'success', 'audio_file': output_file})

    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)

